### ISSUE TITLE
Tutorial 2: density plot for one variable does not display correctly

### ISSUE THREAD

**Issue by vankesteren** [thomvolker/OSWS_Synthetic#3]
see here: it displays a bar chart

![image](https://user-images.githubusercontent.com/11596858/217585577-a9a2964a-c36c-44f7-a5dc-09753f78b25f.png)

**Comment by thomvolker** [comment]
Thanks; fixed it (commit [8655156](https://github.com/thomvolker/OSWS_Synthetic/commit/8655156e860a2c3c27a02d1f5b7a7079ea4ee8ca)). Forgot to change the object names in the results chunk.
